# Generated by Django 5.1.3 on 2024-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order_pack",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
