# Generated by Django 5.1.3 on 2024-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0004_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Working day", unique=True)),
            ],
        ),
    ]
