# Generated by Django 5.1.3 on 2024-11-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0006_productstorestatistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_mean",
                    models.FloatField(
                        blank=True,
                        help_text="Mean sales for the product at the store",
                        null=True,
                    ),
                ),
                (
                    "sales_std",
                    models.FloatField(
                        blank=True,
                        help_text="Sales standard deviation for the product at the store",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="im.product"
                    ),
                ),
            ],
        ),
    ]
