# Generated by Django 5.1.3 on 2024-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0007_productstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstatistics",
            name="S",
            field=models.FloatField(
                blank=True, help_text="S: max threshold", null=True
            ),
        ),
        migrations.AddField(
            model_name="productstorestatistics",
            name="S",
            field=models.FloatField(
                blank=True, help_text="S: max threshold", null=True
            ),
        ),
    ]
