# Generated by Django 5.1.3 on 2024-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0008_productstatistics_s_productstorestatistics_s"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="S_days",
            field=models.FloatField(
                default=30, help_text="For how many days should I order a product"
            ),
        ),
    ]
