# Generated by Django 5.1.3 on 2024-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0009_product_s_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="inflight",
            field=models.BooleanField(default=False),
        ),
    ]
