# Generated by Django 5.1.3 on 2024-11-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0011_remove_inventory_inflight_alter_store_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(default="", max_length=50),
        ),
    ]
