# Generated by Django 5.1.3 on 2024-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0013_alter_inventory_inventory_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="client_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="manager",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
