# Generated by Django 5.1.3 on 2024-12-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0014_sale_category_sale_client_type_sale_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_rus", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="sale",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="im.region",
            ),
        ),
    ]
