# Generated by Django 5.1.3 on 2024-12-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("im", "0016_alter_inventory_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
